### ISSUE TITLE
No images being displayed, just white opening screen

### ISSUE THREAD

**Issue by ShaunTheSalvo** [hmerritt/ambient-tv#39]
In the last 2-3 days, this app has stopped working suddenly. It loads to the opening white title screen, but then does not proceed from there, just stays with white title screen. No images are displayed.

I've tried on my Google TV, and also my Pixel 3 phone - same result. Also tried older APK's besides the latest - same result.

Happy to help with any further testing that may be required.

**Comment by hmerritt** [comment]
Hello,

Thank you for bringing this up, I can also see that this is the case for me too!

Since it was definitely working not long ago, this is most likely a problem with the server.

I will take a look and report back once it's working again.

Thanks again

**Comment by hmerritt** [comment]
I restarted the server and now it's back!

Will close this issue, but feel free to make another if it ever goes down again.

Thank you

**Comment by ShaunTheSalvo** [comment]
Seems to have worked; now working again perfectly. Thank you so much for your very fast response!
